version: "1"
rules:
  - base: master
    upstream: kfp-tekton:master
    mergeMethod: none # don't automatically merge
    mergeUnstable: false
label: "do-not-merge/hold"
conflictLabel: "needs-rebase"