---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ServiceAccounts
  - ./serviceaccounts/postgresql.yaml

  # Secrets
  - ./secrets/postgresql-secret.yaml

  # PersistentVolumeClaims
  - ./persistentvolumeclaims/postgresql-pv-claim.yaml

  # Deployments
  - ./deployments/postgresql.yaml

  # Services
  - ./services/postgresql.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: postgresql
    newName: quay.io/internaldatahub/postgresql-96-centos7
    newTag: "9.6"
