apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelineloop-controller
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipeline-loops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelineloop-webhook
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipeline-loops
