---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  # Service Accounts
  - ./cache-deployer-sa.yaml
  - ./cache-sa.yaml

  # Cluster Roles
  - ./cache-deployer-clusterrole.yaml

  # Cluster Role Bindings
  - ./cache-deployer-clusterrolebinding.yaml

  # Roles
  - ./cache-deployer-role.yaml
  - ./cache-role.yaml

  # Role Bindings
  - ./cache-deployer-rolebinding.yaml
  - ./cache-rolebinding.yaml

  # Deployments
  - ./cache-deployer-deployment.yaml
  - ./cache-deployment.yaml

  # Services
  - ./cache-service.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: cache-deployer
    newName: quay.io/opendatahub/ds-pipelines-cache-deployer
    newTag: 2.0.0
  - name: cache-server
    newName: quay.io/opendatahub/ds-pipelines-cache-server
    newTag: 2.0.0
