apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kfp-driver
  labels:
    app.kubernetes.io/component: kfp-driver
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: kubeflow-pipeline
subjects:
  - kind: ServiceAccount
    name: kfp-driver
    namespace: openshift-pipelines
roleRef:
  kind: Role
  name: kfp-driver
  apiGroup: rbac.authorization.k8s.io
