apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-writer
    application-crd-id: kubeflow-pipelines
  name: metadata-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      labels:
        app: metadata-writer
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - env:
            - name: NAMESPACE_TO_WATCH
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PIPELINE_RUNTIME
              value: tekton
            - name: ARCHIVE_LOGS
              valueFrom:
                configMapKeyRef:
                  key: archive_logs
                  name: $(ml_pipelines_configuration)
          image: metadata-writer
          name: main
          livenessProbe:
            exec:
              command:
                - pidof
                - python3
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - pidof
                - python3
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
      serviceAccountName: kubeflow-pipelines-metadata-writer
