apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ml-pipelines-ui-proxy-tls
  name: ml-pipeline-ui
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
