apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: ds-pipeline-persistenceagent-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ds-pipeline-persistenceagent-clusterrole
subjects:
  - kind: ServiceAccount
    name: ds-pipeline-persistenceagent
    namespace: data-science-pipelines-v2
