---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  # ServiceAccounts
  - ./serviceaccounts/mysql.yaml

  # PersistentVolumeClaims
  - ./persistentvolumeclaims/mariadb-pv-claim.yaml

  # Deployments
  - ./deployments/mariadb.yaml

  # Services
  - ./services/mysql.yaml

  # CronJobs
  - ./cronjobs/mariadb-backup.yaml

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - params.yaml

images:
  - name: mysql
    newName: registry.redhat.io/rhel8/mariadb-103
    newTag: "1-188"
