apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: mariadb-backup
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "mariadb-backup"
        spec:
          containers:
            - name: mariadb-backup
              image: mysql
              command:
                - /bin/sh
                - '-c'
                - >
                  mysqldump -h mysql -u $MYSQL_USER --password=$MYSQL_PASSWORD
                  --all-databases > mariadb-backup.sql
              env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: $(database_secret)
                      key: username
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: $(database_secret)
                      key: password
                - name: MYSQL_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      key: pipelineDb
                      name: $(pipeline_install_configuration)
                - name: MYSQL_ALLOW_EMPTY_PASSWORD
                  value: "true"
          serviceAccountName: mysql
          restartPolicy: Never
