apiVersion: v1
kind: Service
metadata:
    labels:
        application-crd-id: data-science-pipelines
    name: minio-service
spec:
    ports:
        - name: http
          port: 9000
          protocol: TCP
          targetPort: 9000
    selector:
        app: minio
        application-crd-id: data-science-pipelines
