apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        application-crd-id: data-science-pipelines
    name: minio-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
