---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CustomResourceDefinitions
  - ./customresourcedefinitions/viewers.yaml
  - ./customresourcedefinitions/scheduledworkflows.yaml

  # Roles
  - ./roles/ml-pipeline-persistenceagent-role.yaml
  - ./roles/ml-pipeline-scheduledworkflow-role.yaml
  - ./roles/ml-pipeline-viewer-controller-role.yaml
  - ./roles/ml-pipeline.yaml
  - ./roles/pipeline-runner.yaml

  # Rolebindings
  - ./rolebindings/ml-pipeline-persistenceagent-binding.yaml
  - ./rolebindings/ml-pipeline-scheduledworkflow-binding.yaml
  - ./rolebindings/ml-pipeline-viewer-crd-binding.yaml
  - ./rolebindings/ml-pipeline.yaml
  - ./rolebindings/pipeline-runner-binding.yaml

  # ServiceAccounts
  - ./serviceaccounts/kubeflow-pipelines-container-builder.yaml
  - ./serviceaccounts/kubeflow-pipelines-viewer.yaml
  - ./serviceaccounts/ml-pipeline-persistenceagent.yaml
  - ./serviceaccounts/ml-pipeline-scheduledworkflow.yaml
  - ./serviceaccounts/ml-pipeline-viewer-crd-service-account.yaml
  - ./serviceaccounts/ml-pipeline-visualizationserver.yaml
  - ./serviceaccounts/ml-pipeline.yaml
  - ./serviceaccounts/pipeline-runner.yaml

  # Configmaps
  - ./configmaps/kfp-tekton-config.yaml
  - ./configmaps/pipeline-install-config.yaml

  # Deployments
  - ./deployments/ml-pipeline-persistenceagent.yaml
  - ./deployments/ml-pipeline-scheduledworkflow.yaml
  - ./deployments/ml-pipeline-viewer-crd.yaml
  - ./deployments/ml-pipeline-visualizationserver.yaml
  - ./deployments/ml-pipeline.yaml

  # Services
  - ./services/ml-pipeline-visualizationserver.yaml
  - ./services/ml-pipeline.yaml

  # Monitoring
  - ../prometheus

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kfp-tekton-params-config
    envs:
      - params.env
vars:
  - name: artifact_secret_name
    objref:
      name: kfp-tekton-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.artifact_secret_name
  - name: pipeline_install_configuration
    objref:
      name: kfp-tekton-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.pipeline_install_configuration
  - name: ml_pipelines_configuration
    objref:
      name: kfp-tekton-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.ml_pipelines_configuration
  - name: database_secret
    objref:
      name: kfp-tekton-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.database_secret
  - name: ml_pipelines_ui_configuration
    objref:
      name: kfp-tekton-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.ml_pipelines_ui_configuration
configurations:
  - params.yaml

images:
  - name: persistenceagent
    newName: quay.io/internaldatahub/persistenceagent
    newTag: 1.1.0
  - name: scheduledworkflow
    newName: quay.io/internaldatahub/scheduledworkflow
    newTag: 1.1.0
  - name: viewer-crd-controller
    newName: gcr.io/ml-pipeline/viewer-crd-controller
    newTag: 1.7.0
  - name: visualization-server
    newName: gcr.io/ml-pipeline/visualization-server
    newTag: 1.7.0
  - name: api-server
    newName: quay.io/internaldatahub/api-server
    newTag: 1.1.0
