apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-scheduledworkflow
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-scheduledworkflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline-scheduledworkflow
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: ml-pipeline-scheduledworkflow
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CRON_SCHEDULE_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  key: cronScheduleTimezone
                  name: $(pipeline_install_configuration)
          image: scheduledworkflow
          imagePullPolicy: IfNotPresent
          name: ml-pipeline-scheduledworkflow
          livenessProbe:
            exec:
              command:
                - pidof
                - controller
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - pidof
                - controller
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
      serviceAccountName: ml-pipeline-scheduledworkflow
